/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReglesRouteImport } from './routes/regles'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSparksRouteImport } from './routes/_authenticated/sparks'
import { Route as DecouvrirIndexRouteImport } from './routes/decouvrir.index'
import { Route as DecouvrirStudioRouteImport } from './routes/decouvrir.studio'
import { Route as AuthenticatedDiscoverIndexRouteImport } from './routes/_authenticated/discover.index'
import { Route as AuthenticatedDiscoverStudioRouteImport } from './routes/_authenticated/discover.studio'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthRobloxCallbackRouteImport } from './routes/auth.roblox.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglesRoute = ReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSparksRoute = AuthenticatedSparksRouteImport.update({
  id: '/sparks',
  path: '/sparks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DecouvrirIndexRoute = DecouvrirIndexRouteImport.update({
  id: '/decouvrir/',
  path: '/decouvrir/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirStudioRoute = DecouvrirStudioRouteImport.update({
  id: '/decouvrir/studio',
  path: '/decouvrir/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverIndexRoute =
  AuthenticatedDiscoverIndexRouteImport.update({
    id: '/discover/',
    path: '/discover/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoverStudioRoute =
  AuthenticatedDiscoverStudioRouteImport.update({
    id: '/discover/studio',
    path: '/discover/studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthRobloxCallbackRoute = AuthRobloxCallbackRouteImport.update({
  id: '/roblox/callback',
  path: '/roblox/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sparks': typeof AuthenticatedSparksRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/decouvrir/': typeof DecouvrirIndexRoute
  '/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sparks': typeof AuthenticatedSparksRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/decouvrir': typeof DecouvrirIndexRoute
  '/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/discover': typeof AuthenticatedDiscoverIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sparks': typeof AuthenticatedSparksRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/decouvrir/': typeof DecouvrirIndexRoute
  '/_authenticated/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/_authenticated/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/terms'
    | '/admin'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sparks'
    | '/decouvrir/studio'
    | '/decouvrir/'
    | '/discover/studio'
    | '/messages/$id'
    | '/auth/roblox/callback'
    | '/discover/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/terms'
    | '/admin'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sparks'
    | '/decouvrir/studio'
    | '/decouvrir'
    | '/discover/studio'
    | '/messages/$id'
    | '/auth/roblox/callback'
    | '/discover'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/sparks'
    | '/decouvrir/studio'
    | '/decouvrir/'
    | '/_authenticated/discover/studio'
    | '/_authenticated/messages/$id'
    | '/auth/roblox/callback'
    | '/_authenticated/discover/'
    | '/_authenticated/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccueilRoute: typeof AccueilRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  GuestRoute: typeof GuestRoute
  OnboardingRoute: typeof OnboardingRoute
  ParametresRoute: typeof ParametresRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilRoute: typeof ProfilRoute
  ReglesRoute: typeof ReglesRoute
  TermsRoute: typeof TermsRoute
  DecouvrirStudioRoute: typeof DecouvrirStudioRoute
  DecouvrirIndexRoute: typeof DecouvrirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regles': {
      id: '/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof ReglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sparks': {
      id: '/_authenticated/sparks'
      path: '/sparks'
      fullPath: '/sparks'
      preLoaderRoute: typeof AuthenticatedSparksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/decouvrir/': {
      id: '/decouvrir/'
      path: '/decouvrir'
      fullPath: '/decouvrir/'
      preLoaderRoute: typeof DecouvrirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir/studio': {
      id: '/decouvrir/studio'
      path: '/decouvrir/studio'
      fullPath: '/decouvrir/studio'
      preLoaderRoute: typeof DecouvrirStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover/': {
      id: '/_authenticated/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof AuthenticatedDiscoverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover/studio': {
      id: '/_authenticated/discover/studio'
      path: '/discover/studio'
      fullPath: '/discover/studio'
      preLoaderRoute: typeof AuthenticatedDiscoverStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/roblox/callback': {
      id: '/auth/roblox/callback'
      path: '/roblox/callback'
      fullPath: '/auth/roblox/callback'
      preLoaderRoute: typeof AuthRobloxCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSparksRoute: typeof AuthenticatedSparksRoute
  AuthenticatedDiscoverStudioRoute: typeof AuthenticatedDiscoverStudioRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedDiscoverIndexRoute: typeof AuthenticatedDiscoverIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSparksRoute: AuthenticatedSparksRoute,
  AuthenticatedDiscoverStudioRoute: AuthenticatedDiscoverStudioRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedDiscoverIndexRoute: AuthenticatedDiscoverIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthRobloxCallbackRoute: typeof AuthRobloxCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRobloxCallbackRoute: AuthRobloxCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccueilRoute: AccueilRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  GuestRoute: GuestRoute,
  OnboardingRoute: OnboardingRoute,
  ParametresRoute: ParametresRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilRoute: ProfilRoute,
  ReglesRoute: ReglesRoute,
  TermsRoute: TermsRoute,
  DecouvrirStudioRoute: DecouvrirStudioRoute,
  DecouvrirIndexRoute: DecouvrirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
