/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReglesRouteImport } from './routes/regles'
import { Route as ShopTermsRouteImport } from './routes/shop-terms'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRecentRouteImport } from './routes/_authenticated/recent'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSparksRouteImport } from './routes/_authenticated/sparks'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedWikiRouteImport } from './routes/_authenticated/wiki'
import { Route as DecouvrirIndexRouteImport } from './routes/decouvrir.index'
import { Route as DecouvrirStudioRouteImport } from './routes/decouvrir.studio'
import { Route as LinkTokenRouteImport } from './routes/link.$token'
import { Route as AuthenticatedCommunitiesIndexRouteImport } from './routes/_authenticated/communities.index'
import { Route as AuthenticatedCommunitiesHandleRouteImport } from './routes/_authenticated/communities.$handle'
import { Route as AuthenticatedCommunitiesCreateRouteImport } from './routes/_authenticated/communities.create'
import { Route as AuthenticatedDiscoverIndexRouteImport } from './routes/_authenticated/discover.index'
import { Route as AuthenticatedDiscoverStudioRouteImport } from './routes/_authenticated/discover.studio'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedNewsSlugRouteImport } from './routes/_authenticated/news_.$slug'
import { Route as AuthenticatedNewsAllRouteImport } from './routes/_authenticated/news_.all'
import { Route as AuthenticatedNewsSavedRouteImport } from './routes/_authenticated/news_.saved'
import { Route as AuthenticatedShopBillingRouteImport } from './routes/_authenticated/shop_.billing'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users.$id'
import { Route as AuthRobloxCallbackRouteImport } from './routes/auth.roblox.callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglesRoute = ReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/shop-terms',
  path: '/shop-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecentRoute = AuthenticatedRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSparksRoute = AuthenticatedSparksRouteImport.update({
  id: '/sparks',
  path: '/sparks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWikiRoute = AuthenticatedWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DecouvrirIndexRoute = DecouvrirIndexRouteImport.update({
  id: '/decouvrir/',
  path: '/decouvrir/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirStudioRoute = DecouvrirStudioRouteImport.update({
  id: '/decouvrir/studio',
  path: '/decouvrir/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkTokenRoute = LinkTokenRouteImport.update({
  id: '/link/$token',
  path: '/link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunitiesIndexRoute =
  AuthenticatedCommunitiesIndexRouteImport.update({
    id: '/communities/',
    path: '/communities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesHandleRoute =
  AuthenticatedCommunitiesHandleRouteImport.update({
    id: '/communities/$handle',
    path: '/communities/$handle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesCreateRoute =
  AuthenticatedCommunitiesCreateRouteImport.update({
    id: '/communities/create',
    path: '/communities/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoverIndexRoute =
  AuthenticatedDiscoverIndexRouteImport.update({
    id: '/discover/',
    path: '/discover/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoverStudioRoute =
  AuthenticatedDiscoverStudioRouteImport.update({
    id: '/discover/studio',
    path: '/discover/studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsSlugRoute = AuthenticatedNewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsAllRoute = AuthenticatedNewsAllRouteImport.update({
  id: '/news_/all',
  path: '/news/all',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsSavedRoute = AuthenticatedNewsSavedRouteImport.update({
  id: '/news_/saved',
  path: '/news/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopBillingRoute =
  AuthenticatedShopBillingRouteImport.update({
    id: '/shop_/billing',
    path: '/shop/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthRobloxCallbackRoute = AuthRobloxCallbackRouteImport.update({
  id: '/roblox/callback',
  path: '/roblox/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/shop-terms': typeof ShopTermsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/news': typeof AuthenticatedNewsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recent': typeof AuthenticatedRecentRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/sparks': typeof AuthenticatedSparksRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wiki': typeof AuthenticatedWikiRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/link/$token': typeof LinkTokenRoute
  '/decouvrir/': typeof DecouvrirIndexRoute
  '/communities/$handle': typeof AuthenticatedCommunitiesHandleRoute
  '/communities/create': typeof AuthenticatedCommunitiesCreateRoute
  '/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/news/$slug': typeof AuthenticatedNewsSlugRoute
  '/news/all': typeof AuthenticatedNewsAllRoute
  '/news/saved': typeof AuthenticatedNewsSavedRoute
  '/shop/billing': typeof AuthenticatedShopBillingRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/communities/': typeof AuthenticatedCommunitiesIndexRoute
  '/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/shop-terms': typeof ShopTermsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/news': typeof AuthenticatedNewsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recent': typeof AuthenticatedRecentRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/sparks': typeof AuthenticatedSparksRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wiki': typeof AuthenticatedWikiRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/link/$token': typeof LinkTokenRoute
  '/decouvrir': typeof DecouvrirIndexRoute
  '/communities/$handle': typeof AuthenticatedCommunitiesHandleRoute
  '/communities/create': typeof AuthenticatedCommunitiesCreateRoute
  '/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/news/$slug': typeof AuthenticatedNewsSlugRoute
  '/news/all': typeof AuthenticatedNewsAllRoute
  '/news/saved': typeof AuthenticatedNewsSavedRoute
  '/shop/billing': typeof AuthenticatedShopBillingRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/communities': typeof AuthenticatedCommunitiesIndexRoute
  '/discover': typeof AuthenticatedDiscoverIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accueil': typeof AccueilRoute
  '/auth': typeof AuthRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/guest': typeof GuestRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/privacy': typeof PrivacyRoute
  '/profil': typeof ProfilRoute
  '/regles': typeof ReglesRoute
  '/shop-terms': typeof ShopTermsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recent': typeof AuthenticatedRecentRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/sparks': typeof AuthenticatedSparksRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/wiki': typeof AuthenticatedWikiRoute
  '/decouvrir/studio': typeof DecouvrirStudioRoute
  '/link/$token': typeof LinkTokenRoute
  '/decouvrir/': typeof DecouvrirIndexRoute
  '/_authenticated/communities/$handle': typeof AuthenticatedCommunitiesHandleRoute
  '/_authenticated/communities/create': typeof AuthenticatedCommunitiesCreateRoute
  '/_authenticated/discover/studio': typeof AuthenticatedDiscoverStudioRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/news_/$slug': typeof AuthenticatedNewsSlugRoute
  '/_authenticated/news_/all': typeof AuthenticatedNewsAllRoute
  '/_authenticated/news_/saved': typeof AuthenticatedNewsSavedRoute
  '/_authenticated/shop_/billing': typeof AuthenticatedShopBillingRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/auth/roblox/callback': typeof AuthRobloxCallbackRoute
  '/_authenticated/communities/': typeof AuthenticatedCommunitiesIndexRoute
  '/_authenticated/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/shop-terms'
    | '/terms'
    | '/admin'
    | '/events'
    | '/home'
    | '/news'
    | '/profile'
    | '/recent'
    | '/rewards'
    | '/saved'
    | '/settings'
    | '/shop'
    | '/sparks'
    | '/store'
    | '/support'
    | '/wiki'
    | '/decouvrir/studio'
    | '/link/$token'
    | '/decouvrir/'
    | '/communities/$handle'
    | '/communities/create'
    | '/discover/studio'
    | '/messages/$id'
    | '/news/$slug'
    | '/news/all'
    | '/news/saved'
    | '/shop/billing'
    | '/users/$id'
    | '/auth/roblox/callback'
    | '/communities/'
    | '/discover/'
    | '/messages/'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/shop-terms'
    | '/terms'
    | '/admin'
    | '/events'
    | '/home'
    | '/news'
    | '/profile'
    | '/recent'
    | '/rewards'
    | '/saved'
    | '/settings'
    | '/shop'
    | '/sparks'
    | '/store'
    | '/support'
    | '/wiki'
    | '/decouvrir/studio'
    | '/link/$token'
    | '/decouvrir'
    | '/communities/$handle'
    | '/communities/create'
    | '/discover/studio'
    | '/messages/$id'
    | '/news/$slug'
    | '/news/all'
    | '/news/saved'
    | '/shop/billing'
    | '/users/$id'
    | '/auth/roblox/callback'
    | '/communities'
    | '/discover'
    | '/messages'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accueil'
    | '/auth'
    | '/community-guidelines'
    | '/conditions'
    | '/confidentialite'
    | '/guest'
    | '/onboarding'
    | '/parametres'
    | '/privacy'
    | '/profil'
    | '/regles'
    | '/shop-terms'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/events'
    | '/_authenticated/home'
    | '/_authenticated/news'
    | '/_authenticated/profile'
    | '/_authenticated/recent'
    | '/_authenticated/rewards'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/shop'
    | '/_authenticated/sparks'
    | '/_authenticated/store'
    | '/_authenticated/support'
    | '/_authenticated/wiki'
    | '/decouvrir/studio'
    | '/link/$token'
    | '/decouvrir/'
    | '/_authenticated/communities/$handle'
    | '/_authenticated/communities/create'
    | '/_authenticated/discover/studio'
    | '/_authenticated/messages/$id'
    | '/_authenticated/news_/$slug'
    | '/_authenticated/news_/all'
    | '/_authenticated/news_/saved'
    | '/_authenticated/shop_/billing'
    | '/_authenticated/users/$id'
    | '/auth/roblox/callback'
    | '/_authenticated/communities/'
    | '/_authenticated/discover/'
    | '/_authenticated/messages/'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccueilRoute: typeof AccueilRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  GuestRoute: typeof GuestRoute
  OnboardingRoute: typeof OnboardingRoute
  ParametresRoute: typeof ParametresRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilRoute: typeof ProfilRoute
  ReglesRoute: typeof ReglesRoute
  ShopTermsRoute: typeof ShopTermsRoute
  TermsRoute: typeof TermsRoute
  DecouvrirStudioRoute: typeof DecouvrirStudioRoute
  LinkTokenRoute: typeof LinkTokenRoute
  DecouvrirIndexRoute: typeof DecouvrirIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regles': {
      id: '/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof ReglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-terms': {
      id: '/shop-terms'
      path: '/shop-terms'
      fullPath: '/shop-terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recent': {
      id: '/_authenticated/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AuthenticatedRecentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sparks': {
      id: '/_authenticated/sparks'
      path: '/sparks'
      fullPath: '/sparks'
      preLoaderRoute: typeof AuthenticatedSparksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wiki': {
      id: '/_authenticated/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof AuthenticatedWikiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/decouvrir/': {
      id: '/decouvrir/'
      path: '/decouvrir'
      fullPath: '/decouvrir/'
      preLoaderRoute: typeof DecouvrirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir/studio': {
      id: '/decouvrir/studio'
      path: '/decouvrir/studio'
      fullPath: '/decouvrir/studio'
      preLoaderRoute: typeof DecouvrirStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/$token': {
      id: '/link/$token'
      path: '/link/$token'
      fullPath: '/link/$token'
      preLoaderRoute: typeof LinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/communities/': {
      id: '/_authenticated/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AuthenticatedCommunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities/$handle': {
      id: '/_authenticated/communities/$handle'
      path: '/communities/$handle'
      fullPath: '/communities/$handle'
      preLoaderRoute: typeof AuthenticatedCommunitiesHandleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities/create': {
      id: '/_authenticated/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof AuthenticatedCommunitiesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover/': {
      id: '/_authenticated/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof AuthenticatedDiscoverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover/studio': {
      id: '/_authenticated/discover/studio'
      path: '/discover/studio'
      fullPath: '/discover/studio'
      preLoaderRoute: typeof AuthenticatedDiscoverStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news_/$slug': {
      id: '/_authenticated/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof AuthenticatedNewsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news_/all': {
      id: '/_authenticated/news_/all'
      path: '/news/all'
      fullPath: '/news/all'
      preLoaderRoute: typeof AuthenticatedNewsAllRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news_/saved': {
      id: '/_authenticated/news_/saved'
      path: '/news/saved'
      fullPath: '/news/saved'
      preLoaderRoute: typeof AuthenticatedNewsSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop_/billing': {
      id: '/_authenticated/shop_/billing'
      path: '/shop/billing'
      fullPath: '/shop/billing'
      preLoaderRoute: typeof AuthenticatedShopBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/roblox/callback': {
      id: '/auth/roblox/callback'
      path: '/roblox/callback'
      fullPath: '/auth/roblox/callback'
      preLoaderRoute: typeof AuthRobloxCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecentRoute: typeof AuthenticatedRecentRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSparksRoute: typeof AuthenticatedSparksRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWikiRoute: typeof AuthenticatedWikiRoute
  AuthenticatedCommunitiesHandleRoute: typeof AuthenticatedCommunitiesHandleRoute
  AuthenticatedCommunitiesCreateRoute: typeof AuthenticatedCommunitiesCreateRoute
  AuthenticatedDiscoverStudioRoute: typeof AuthenticatedDiscoverStudioRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedNewsSlugRoute: typeof AuthenticatedNewsSlugRoute
  AuthenticatedNewsAllRoute: typeof AuthenticatedNewsAllRoute
  AuthenticatedNewsSavedRoute: typeof AuthenticatedNewsSavedRoute
  AuthenticatedShopBillingRoute: typeof AuthenticatedShopBillingRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedCommunitiesIndexRoute: typeof AuthenticatedCommunitiesIndexRoute
  AuthenticatedDiscoverIndexRoute: typeof AuthenticatedDiscoverIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecentRoute: AuthenticatedRecentRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSparksRoute: AuthenticatedSparksRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWikiRoute: AuthenticatedWikiRoute,
  AuthenticatedCommunitiesHandleRoute: AuthenticatedCommunitiesHandleRoute,
  AuthenticatedCommunitiesCreateRoute: AuthenticatedCommunitiesCreateRoute,
  AuthenticatedDiscoverStudioRoute: AuthenticatedDiscoverStudioRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedNewsSlugRoute: AuthenticatedNewsSlugRoute,
  AuthenticatedNewsAllRoute: AuthenticatedNewsAllRoute,
  AuthenticatedNewsSavedRoute: AuthenticatedNewsSavedRoute,
  AuthenticatedShopBillingRoute: AuthenticatedShopBillingRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedCommunitiesIndexRoute: AuthenticatedCommunitiesIndexRoute,
  AuthenticatedDiscoverIndexRoute: AuthenticatedDiscoverIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthRobloxCallbackRoute: typeof AuthRobloxCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRobloxCallbackRoute: AuthRobloxCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccueilRoute: AccueilRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  GuestRoute: GuestRoute,
  OnboardingRoute: OnboardingRoute,
  ParametresRoute: ParametresRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilRoute: ProfilRoute,
  ReglesRoute: ReglesRoute,
  ShopTermsRoute: ShopTermsRoute,
  TermsRoute: TermsRoute,
  DecouvrirStudioRoute: DecouvrirStudioRoute,
  LinkTokenRoute: LinkTokenRoute,
  DecouvrirIndexRoute: DecouvrirIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
